FROM ubuntu:16.04
FROM python:3.7
LABEL Maintainer="Gianni Alessandroni"
LABEL Email="<gianni@w1s3.com>"
LABEL Company="WISE ROBOTICS SRLS"
LABEL Product="FDD_DOCKER"
LABEL Release="2019-10-05"
LABEL Copyright="(C) 2019 Wise Robotics Srls"

ENV MSSQLTOOLS_VERSION=17.1.0.0
ENV PATH /opt/mssql-tools/bin:$PATH

RUN apt-get update \
    && apt-get install -y curl apt-transport-https locales \
    && locale-gen "en_US.UTF-8" \
    && apt-get update \
    && apt-get remove -y curl apt-transport-https \
    && rm -f /etc/apt/sources.list.d/msprod.list \
    && rm -rf /var/lib/apt/lists/*

# Install some dependencies
RUN apt-get update && apt-get install -y \
	nano \
	python-dev \
	build-essential \
	curl \
	unzip \
	vim \
	wget \
	yasm \
	python-tk \
	python-numpy \
	python3-dev \
	python3-tk \
	python3-numpy \
	ant \
	default-jdk \
	doxygen \
	apt-transport-https \
	&& \
	apt-get clean && \
	apt-get autoremove && \
	rm -rf /var/lib/apt/lists/*

# Install pip
RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
	python get-pip.py && \
	rm get-pip.py

# Add SNI support to Python
RUN pip --no-cache-dir install \
		pyopenssl \
		ndg-httpsclient \
		pyasn1

# Install useful Python packages using apt-get to avoid version incompatibilities with Tensorflow binary
# especially numpy, scipy, skimage and sklearn (see https://github.com/tensorflow/tensorflow/issues/2034)
RUN apt-get update && apt-get install -y \
		python-numpy \
		python3-numpy \
		python-nose \
		python-h5py \
		python-skimage \
		python-matplotlib \
		python3-matplotlib \
		python-pandas \
		python3-pandas \
		python-sklearn \
		python-sympy \
		&& \
	apt-get clean && \
	apt-get autoremove && \
	rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y \

    python3-flask \
		python3-pip \
		&& \
	apt-get clean && \
	apt-get autoremove && \
	rm -rf /var/lib/apt/lists/*

COPY requirements.txt /root/
RUN pip3 install -r /root/requirements.txt

ENV PYTHONIOENCODING=utf-8
ENV CAPI https://application.quake.cloud

# Expose Ports for helloworld (80)
EXPOSE 5000

# COPY testredis.py testsql.py /root/
COPY code/* /root/
WORKDIR /root

ENTRYPOINT ["python3", "main.py"]

